version: "3.9"

services:
  api:
    build: .
    container_name: churn-fastapi
    ports:
      - "8000:8000"
    restart: always

  streamlit:
    image: python:3.11-slim
    container_name: churn-streamlit
    working_dir: /app
    volumes:
      - .:/app
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
